[program:gerenciador-whatsapp-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/gerenciador-mensagens/artisan queue:work redis --queue=whatsapp-messages --sleep=3 --tries=1 --timeout=120
directory=/var/www/gerenciador-mensagens
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/gerenciador-whatsapp-worker.log
stopwaitsecs=180
