<?php

namespace App\Enums;

enum PermissionSlug: string
{
    case DashboardView = 'dashboard.view';
    case UsersView = 'users.view';
    case UsersManage = 'users.manage';
    case SettingsView = 'settings.view';
    case SettingsManage = 'settings.manage';
    case AuditView = 'audit.view';
    case ProfileManage = 'profile.manage';
    case ContactsView = 'contacts.view';
    case ContactsCreate = 'contacts.create';
    case ContactsUpdate = 'contacts.update';
    case ContactsDelete = 'contacts.delete';
    case ContactsRestore = 'contacts.restore';
    case ContactsExport = 'contacts.export';
    case ContactsImport = 'contacts.import';
    case ContactsManageTags = 'contacts.manage_tags';
    case ContactsMarkDoNotContact = 'contacts.mark_do_not_contact';
    case ContactsViewSensitiveData = 'contacts.view_sensitive_data';
    case WhatsAppConnectionView = 'whatsapp.connection.view';
    case WhatsAppConnectionManage = 'whatsapp.connection.manage';
    case WhatsAppConnectionDisconnect = 'whatsapp.connection.disconnect';
    case WhatsAppConnectionClearSession = 'whatsapp.connection.clear_session';
    case WhatsAppTestMessageSend = 'whatsapp.test_message.send';
    case WhatsAppEventsView = 'whatsapp.events.view';
    case MessageTemplatesView = 'message_templates.view';
    case MessageTemplatesCreate = 'message_templates.create';
    case MessageTemplatesUpdate = 'message_templates.update';
    case MessageTemplatesDelete = 'message_templates.delete';
    case MessageTemplatesRestore = 'message_templates.restore';
    case MessageTemplatesDuplicate = 'message_templates.duplicate';
    case MessageBatchesView = 'message_batches.view';
    case MessageBatchesCreate = 'message_batches.create';
    case MessageBatchesUpdate = 'message_batches.update';
    case MessageBatchesCancel = 'message_batches.cancel';
    case MessageBatchesDuplicate = 'message_batches.duplicate';
    case MessageBatchesViewRecipients = 'message_batches.view_recipients';
    case MessageBatchesExportPreview = 'message_batches.export_preview';
    case MessageProcessingView = 'message_processing.view';
    case MessageProcessingStart = 'message_processing.start';
    case MessageProcessingPause = 'message_processing.pause';
    case MessageProcessingResume = 'message_processing.resume';
    case MessageProcessingStop = 'message_processing.stop';
    case MessageProcessingCancelRecipient = 'message_processing.cancel_recipient';
    case MessageProcessingRetry = 'message_processing.retry';
    case MessageProcessingViewAttempts = 'message_processing.view_attempts';
    case MessageProcessingManageSettings = 'message_processing.manage_settings';
    case MessageProcessingRunMaintenance = 'message_processing.run_maintenance';
    case HistoriesView = 'histories.view';
    case HistoriesViewMessageContent = 'histories.view_message_content';
    case HistoriesViewAttempts = 'histories.view_attempts';
    case HistoriesViewTechnicalDetails = 'histories.view_technical_details';
    case HistoriesExport = 'histories.export';
    case ReportsView = 'reports.view';
    case ReportsExport = 'reports.export';
    case ReportsViewContactData = 'reports.view_contact_data';
    case ReportsViewOperationalMetrics = 'reports.view_operational_metrics';
    case MonitoringView = 'monitoring.view';
    case MonitoringViewSensitiveDetails = 'monitoring.view_sensitive_details';
    case MonitoringRunDiagnostics = 'monitoring.run_diagnostics';
    case MaintenanceView = 'maintenance.view';
    case MaintenanceSyncCounters = 'maintenance.sync_counters';
    case MaintenanceRecoverStuck = 'maintenance.recover_stuck';
    case MaintenanceRetryEligible = 'maintenance.retry_eligible';
    case MaintenanceCleanupLogs = 'maintenance.cleanup_logs';
    case MaintenanceApplyRetention = 'maintenance.apply_retention';
    case MaintenanceRunCommands = 'maintenance.run_commands';
    case InboxView = 'inbox.view';
    case InboxViewAll = 'inbox.view_all';
    case InboxViewMessageContent = 'inbox.view_message_content';
    case InboxReply = 'inbox.reply';
    case InboxAssign = 'inbox.assign';
    case InboxChangeStatus = 'inbox.change_status';
    case InboxChangePriority = 'inbox.change_priority';
    case InboxManageTags = 'inbox.manage_tags';
    case InboxAddNotes = 'inbox.add_notes';
    case InboxEditNotes = 'inbox.edit_notes';
    case InboxArchive = 'inbox.archive';
    case InboxBlock = 'inbox.block';
    case InboxMarkDoNotContact = 'inbox.mark_do_not_contact';
    case InboxAssociateContact = 'inbox.associate_contact';
    case InboxViewMetrics = 'inbox.view_metrics';

    public function label(): string
    {
        return match ($this) {
            self::DashboardView => 'Visualizar dashboard',
            self::UsersView => 'Visualizar usuarios',
            self::UsersManage => 'Gerenciar usuarios',
            self::SettingsView => 'Visualizar configuracoes',
            self::SettingsManage => 'Gerenciar configuracoes',
            self::AuditView => 'Visualizar auditoria',
            self::ProfileManage => 'Gerenciar proprio perfil',
            self::ContactsView => 'Visualizar contatos',
            self::ContactsCreate => 'Cadastrar contatos',
            self::ContactsUpdate => 'Editar contatos',
            self::ContactsDelete => 'Excluir contatos',
            self::ContactsRestore => 'Restaurar contatos',
            self::ContactsExport => 'Exportar contatos',
            self::ContactsImport => 'Importar contatos',
            self::ContactsManageTags => 'Gerenciar etiquetas',
            self::ContactsMarkDoNotContact => 'Marcar nao contatar',
            self::ContactsViewSensitiveData => 'Visualizar dados sensiveis de contatos',
            self::WhatsAppConnectionView => 'Visualizar conexao WhatsApp',
            self::WhatsAppConnectionManage => 'Gerenciar conexao WhatsApp',
            self::WhatsAppConnectionDisconnect => 'Desconectar WhatsApp',
            self::WhatsAppConnectionClearSession => 'Excluir sessao WhatsApp',
            self::WhatsAppTestMessageSend => 'Enviar mensagem de teste WhatsApp',
            self::WhatsAppEventsView => 'Visualizar eventos WhatsApp',
            self::MessageTemplatesView => 'Visualizar modelos de mensagens',
            self::MessageTemplatesCreate => 'Criar modelos de mensagens',
            self::MessageTemplatesUpdate => 'Editar modelos de mensagens',
            self::MessageTemplatesDelete => 'Excluir modelos de mensagens',
            self::MessageTemplatesRestore => 'Restaurar modelos de mensagens',
            self::MessageTemplatesDuplicate => 'Duplicar modelos de mensagens',
            self::MessageBatchesView => 'Visualizar lotes de mensagens',
            self::MessageBatchesCreate => 'Criar lotes de mensagens',
            self::MessageBatchesUpdate => 'Editar lotes de mensagens',
            self::MessageBatchesCancel => 'Cancelar lotes de mensagens',
            self::MessageBatchesDuplicate => 'Duplicar lotes de mensagens',
            self::MessageBatchesViewRecipients => 'Visualizar destinatarios de lotes',
            self::MessageBatchesExportPreview => 'Exportar previa de lotes',
            self::MessageProcessingView => 'Visualizar processamento de mensagens',
            self::MessageProcessingStart => 'Iniciar processamento de lote',
            self::MessageProcessingPause => 'Pausar processamento de lote',
            self::MessageProcessingResume => 'Retomar processamento de lote',
            self::MessageProcessingStop => 'Parar processamento de lote',
            self::MessageProcessingCancelRecipient => 'Cancelar destinatario do processamento',
            self::MessageProcessingRetry => 'Tentar novamente destinatario com falha',
            self::MessageProcessingViewAttempts => 'Visualizar tentativas de envio',
            self::MessageProcessingManageSettings => 'Gerenciar configuracoes de envio',
            self::MessageProcessingRunMaintenance => 'Executar manutencao de processamento',
            self::HistoriesView => 'Visualizar historicos',
            self::HistoriesViewMessageContent => 'Visualizar conteudo de mensagens no historico',
            self::HistoriesViewAttempts => 'Visualizar tentativas no historico',
            self::HistoriesViewTechnicalDetails => 'Visualizar detalhes tecnicos do historico',
            self::HistoriesExport => 'Exportar historicos',
            self::ReportsView => 'Visualizar relatorios',
            self::ReportsExport => 'Exportar relatorios',
            self::ReportsViewContactData => 'Visualizar dados de contato em relatorios',
            self::ReportsViewOperationalMetrics => 'Visualizar metricas operacionais',
            self::MonitoringView => 'Visualizar monitoramento',
            self::MonitoringViewSensitiveDetails => 'Visualizar detalhes sensiveis do monitoramento',
            self::MonitoringRunDiagnostics => 'Executar diagnosticos',
            self::MaintenanceView => 'Visualizar manutencao',
            self::MaintenanceSyncCounters => 'Sincronizar contadores',
            self::MaintenanceRecoverStuck => 'Recuperar mensagens presas',
            self::MaintenanceRetryEligible => 'Tentar novamente mensagens elegiveis',
            self::MaintenanceCleanupLogs => 'Limpar logs e arquivos temporarios',
            self::MaintenanceApplyRetention => 'Aplicar retencao de dados',
            self::MaintenanceRunCommands => 'Executar comandos de manutencao',
            self::InboxView => 'Visualizar caixa de entrada',
            self::InboxViewAll => 'Visualizar todas as conversas',
            self::InboxViewMessageContent => 'Visualizar conteudo de conversas',
            self::InboxReply => 'Responder manualmente conversas',
            self::InboxAssign => 'Atribuir conversas',
            self::InboxChangeStatus => 'Alterar status de conversas',
            self::InboxChangePriority => 'Alterar prioridade de conversas',
            self::InboxManageTags => 'Gerenciar etiquetas de conversas',
            self::InboxAddNotes => 'Adicionar notas internas',
            self::InboxEditNotes => 'Editar notas internas',
            self::InboxArchive => 'Arquivar conversas',
            self::InboxBlock => 'Bloquear conversas',
            self::InboxMarkDoNotContact => 'Marcar contato como nao contatar pela conversa',
            self::InboxAssociateContact => 'Associar contato a conversa',
            self::InboxViewMetrics => 'Visualizar metricas da caixa de entrada',
        };
    }
}
